In [2]:
from pathlib import Path
import sys

# Add the project root directory to sys.path
sys.path.append(str(Path().resolve().parent))
from src.constants.paths import SECRET_PATH

SECRET_PATH

from src.processing.pde_ple import PDE, PLE, es

/opt/app-root/src/uc202-ipn-rex/.venv/lib/python3.11/site-packages/elasticsearch/_sync/client/__init__.py:397: SecurityWarning: Connecting to 'https://noeyyalp.noe.edf.fr:29203' using TLS with verify_certs=False is insecure
  _transport = transport_class(

In [1]:
import pymupdf

In [17]:
root_path = "s3://bkt-pud-uc/uc202-rex/FA3_useful_files_final/Services.004/G-Environnement.007/01 - Réseau HSE - suivi titulaires/01 - Suivi des documents/01 - Tableau de suivi/Courriers transmis aux etps/"
path=PLE.s3.ls(root_path)['path'][0]
path

'bkt-pud-uc/uc202-rex/FA3_useful_files_final/Services.004/G-Environnement.007/01 - Réseau HSE - suivi titulaires/01 - Suivi des documents/01 - Tableau de suivi/Courriers transmis aux etps/D458517040153 [ ] [ ].pdf'

In [32]:
ch = "\\atlas.edf.fr\CO\dipnn-fla3\Services.004\G-Environnement.007\01 - Réseau HSE - suivi titulaires\04 - Réunions Etps mensuelles\Réunion Ets 2011\1 - Réunion de chantier du 23 février 2011\VHE au 18 02 2011\Suivi Enviro VE et VHE 2010  au 18 02 2011 annexe"
len(ch)

248

In [ ]:
import polars as pl


def get_all_file_paths(root_path):
    useful_extensions = {
        ".pdf",
        ".doc",
        ".docx",
        ".txt",
        ".rtf",
        ".odt",
        ".ppt",
        ".pptx",
        ".pps",
        ".ppsx",
        ".odp",
        ".xls",
        ".xlsx",
        ".xlsb",
        ".ods",
        ".csv",
    }

Reached 2000 files
Reached 4000 files
Reached 6000 files
Reached 8000 files

In [30]:
len(file_paths)

9396

In [ ]:
from elasticsearch import Elasticsearch, helpers
import pandas as pd
import os
ENDPOINT=""
es = Elasticsearch(
    hosts=ENDPOINT,
    verify_certs=False,
    http_auth=(USERNAME_elastic, MDP_elastic),
)

In [19]:
import pandas as pd
import polars as pl
import chardet

# Define the useful extensions set
useful_extensions = {
    ".pdf",
    ".Pdf",
    ".doc",
    ".docx",
    ".docm",
    ".txt",
    ".rtf",
    ".odt",
    ".ppt",
    ".pptx",
    ".pps",
    ".ppsx",
    ".odp",
    ".xls",
    ".xlsx",
    ".xlsm",
    ".xlsb",
    ".ods",
    ".csv",
}


# Function to detect file encoding
def detect_encoding(file_path):
    with open(file_path, "rb") as f:
        result = chardet.detect(f.read())
    return result["encoding"]

In [ ]:
encoding1 = detect_encoding(
    r"\\atlas.edf.fr\CO\dipnn-fla3\Archives-Temporaires.010\24-BASE-DONNEES.024\3-Export_RITM1937379 EXPORTS POUR DATA IA FACTORY\N1 Services 004\EDV.037.csv"
)
file1 = r"\\atlas.edf.fr\CO\dipnn-fla3\Archives-Temporaires.010\24-BASE-DONNEES.024\3-Export_RITM1937379 EXPORTS POUR DATA IA FACTORY\N1 Services 004\G-Environnement.007.csv"
file2 = r"\\atlas.edf.fr\CO\dipnn-fla3\Archives-Temporaires.010\24-BASE-DONNEES.024\3-Export_RITM1937379 EXPORTS POUR DATA IA FACTORY\N1 Services 004\W-Lot-Ingenierie-Locale.023.csv"

df1 = pl.read_csv(
    file1,
    skip_rows=1,
    has_header=False,
    encoding=encoding1,
    ignore_errors=True,
    separator=";",
)
df2 = pl.read_csv(
    file2,
    skip_rows=1,
    has_header=False,
    encoding=encoding1,
    ignore_errors=True,
    separator=";",
)

# Concatenate the DataFrames


# Filter by file extension

TypeError: concat() got an unexpected keyword argument 'ignore_index'

In [ ]:
combined_df = pl.concat([df1, df2])
df=combined_df
first_row = df.row(0)

# Rename the columns using the values from the first row
df = df.rename(dict(zip(df.columns, first_row)))

# Remove the first row if it is no longer needed
df = df.slice(1)

In [28]:
df

shape: (3_771_209, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ Nom titre du ┆ Type        ┆ Date de     ┆ Date de     ┆ Nom du créa ┆ Chemin      ┆ Taille du   │
│ fichier      ┆ extension   ┆ création du ┆ dernière    ┆ teur/dernie ┆ d'accès     ┆ fichier     │
│ ---          ┆ de fichier  ┆ fichier     ┆ modificatio ┆ r modifi…   ┆ ---         ┆ ---         │
│ str          ┆ ---         ┆ ---         ┆ n           ┆ ---         ┆ str         ┆ str         │
│              ┆ str         ┆ str         ┆ ---         ┆ str         ┆             ┆             │
│              ┆             ┆             ┆ str         ┆             ┆             ┆             │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ ECFA070459.d ┆ .docx       ┆ 05/04/2019  ┆ 05/04/2019  ┆ O:S-1-5-21- ┆ Q:\CO\DIPNN ┆ 1027830     │
│ ocx          ┆             ┆ 11:15:34    ┆ 11:15:36    ┆ 2415383333- ┆ -FLA3\Servi ┆             │
│              ┆             ┆             ┆             ┆ 40638412…   ┆ ces.004\…   ┆             │
│ Gestion      ┆ .pptx       ┆ 02/09/2020  ┆ 02/09/2020  ┆ O:S-1-5-21- ┆ Q:\CO\DIPNN ┆ 233513      │
│ bouteilles   ┆             ┆ 09:43:43    ┆ 10:12:59    ┆ 2415383333- ┆ -FLA3\Servi ┆             │
│ de gaz.pptx  ┆             ┆             ┆             ┆ 40638412…   ┆ ces.004\…   ┆             │
│ Réchauffemen ┆ .docx       ┆ 16/05/2019  ┆ 16/05/2019  ┆ O:S-1-5-21- ┆ Q:\CO\DIPNN ┆ 1261520     │
│ t Climatique ┆             ┆ 14:32:47    ┆ 14:31:30    ┆ 2415383333- ┆ -FLA3\Servi ┆             │
│ -Trans…      ┆             ┆             ┆             ┆ 40638412…   ┆ ces.004\…   ┆             │
│ S24-2018     ┆ .xlsx       ┆ 15/06/2018  ┆ 15/06/2018  ┆ O:S-1-5-21- ┆ Q:\CO\DIPNN ┆ 16383       │
│ stat         ┆             ┆ 14:53:52    ┆ 14:53:53    ┆ 2415383333- ┆ -FLA3\Servi ┆             │
│ AFA.xlsx     ┆             ┆             ┆             ┆ 40638412…   ┆ ces.004\…   ┆             │
│ Sensibilisat ┆ .ppt        ┆ 23/07/2019  ┆ 24/07/2019  ┆ ATLAS\A3427 ┆ Q:\CO\DIPNN ┆ 43713024    │
│ ion Enviro   ┆             ┆ 15:04:16    ┆ 10:34:21    ┆ 4           ┆ -FLA3\Servi ┆             │
│ juin 20…     ┆             ┆             ┆             ┆             ┆ ces.004\…   ┆             │
│ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ 3HLC2209DO-I ┆ .jpg        ┆ 19/02/2025  ┆ 19/02/2025  ┆ ATLAS\LK2BA ┆ Q:\CO\DIPNN ┆ 2274671     │
│ n.jpg        ┆             ┆ 10:07:04    ┆ 09:15:02    ┆ 2CL         ┆ -FLA3\Servi ┆             │
│              ┆             ┆             ┆             ┆             ┆ ces.004\…   ┆             │
│ 3HLC2209DO.j ┆ .jpg        ┆ 19/02/2025  ┆ 19/02/2025  ┆ ATLAS\LK2BA ┆ Q:\CO\DIPNN ┆ 413373      │
│ pg           ┆             ┆ 10:07:00    ┆ 09:27:05    ┆ 2CL         ┆ -FLA3\Servi ┆             │
│              ┆             ┆             ┆             ┆             ┆ ces.004\…   ┆             │
│ Image sans   ┆ .jpg        ┆ 11/03/2025  ┆ 11/03/2025  ┆ ATLAS\LK2BA ┆ Q:\CO\DIPNN ┆ 1131331     │
│ titre.jpg    ┆             ┆ 08:33:59    ┆ 08:38:12    ┆ 2CL         ┆ -FLA3\Servi ┆             │
│              ┆             ┆             ┆             ┆             ┆ ces.004\…   ┆             │
│ Inked3HLB220 ┆ .jpg        ┆ 19/02/2025  ┆ 19/02/2025  ┆ ATLAS\LK2BA ┆ Q:\CO\DIPNN ┆ 2251904     │
│ 9DO-In.jpg   ┆             ┆ 10:07:14    ┆ 09:53:03    ┆ 2CL         ┆ -FLA3\Servi ┆             │
│              ┆             ┆             ┆             ┆             ┆ ces.004\…   ┆             │
│ volet antino ┆ .jpg        ┆ 19/02/2025  ┆ 02/12/2024  ┆ ATLAS\LK2BA ┆ Q:\CO\DIPNN ┆ 1484027     │
│ ndation.jpg  ┆             ┆ 10:07:23    ┆ 16:29:40    ┆ 2CL         ┆ -FLA3\Servi ┆             │
│              ┆             ┆             ┆             ┆             ┆ ces.004\…   ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [31]:
df.columns

['Nom titre du fichier',
 'Type extension de fichier',
 'Date de création du fichier',
 'Date de dernière modification',
 'Nom du créateur/dernier modificateur',
 "Chemin d'accès",
 'Taille du fichier']

In [32]:
df = df.filter(
    pl.col("Type extension de fichier").str.to_lowercase().is_in(useful_extensions)
)

# Transform the "Chemin d'accès" column
df = df.with_columns(
    pl.col("Chemin d'accès").str.replace(r"^Q:\\", r"\\atlas.edf.fr\\")
)

In [33]:
df

shape: (1_802_054, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ Nom titre du ┆ Type        ┆ Date de     ┆ Date de     ┆ Nom du créa ┆ Chemin      ┆ Taille du   │
│ fichier      ┆ extension   ┆ création du ┆ dernière    ┆ teur/dernie ┆ d'accès     ┆ fichier     │
│ ---          ┆ de fichier  ┆ fichier     ┆ modificatio ┆ r modifi…   ┆ ---         ┆ ---         │
│ str          ┆ ---         ┆ ---         ┆ n           ┆ ---         ┆ str         ┆ str         │
│              ┆ str         ┆ str         ┆ ---         ┆ str         ┆             ┆             │
│              ┆             ┆             ┆ str         ┆             ┆             ┆             │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ ECFA070459.d ┆ .docx       ┆ 05/04/2019  ┆ 05/04/2019  ┆ O:S-1-5-21- ┆ \\atlas.edf ┆ 1027830     │
│ ocx          ┆             ┆ 11:15:34    ┆ 11:15:36    ┆ 2415383333- ┆ .fr\\CO\DIP ┆             │
│              ┆             ┆             ┆             ┆ 40638412…   ┆ NN-FLA3\…   ┆             │
│ Gestion      ┆ .pptx       ┆ 02/09/2020  ┆ 02/09/2020  ┆ O:S-1-5-21- ┆ \\atlas.edf ┆ 233513      │
│ bouteilles   ┆             ┆ 09:43:43    ┆ 10:12:59    ┆ 2415383333- ┆ .fr\\CO\DIP ┆             │
│ de gaz.pptx  ┆             ┆             ┆             ┆ 40638412…   ┆ NN-FLA3\…   ┆             │
│ Réchauffemen ┆ .docx       ┆ 16/05/2019  ┆ 16/05/2019  ┆ O:S-1-5-21- ┆ \\atlas.edf ┆ 1261520     │
│ t Climatique ┆             ┆ 14:32:47    ┆ 14:31:30    ┆ 2415383333- ┆ .fr\\CO\DIP ┆             │
│ -Trans…      ┆             ┆             ┆             ┆ 40638412…   ┆ NN-FLA3\…   ┆             │
│ S24-2018     ┆ .xlsx       ┆ 15/06/2018  ┆ 15/06/2018  ┆ O:S-1-5-21- ┆ \\atlas.edf ┆ 16383       │
│ stat         ┆             ┆ 14:53:52    ┆ 14:53:53    ┆ 2415383333- ┆ .fr\\CO\DIP ┆             │
│ AFA.xlsx     ┆             ┆             ┆             ┆ 40638412…   ┆ NN-FLA3\…   ┆             │
│ Sensibilisat ┆ .ppt        ┆ 23/07/2019  ┆ 24/07/2019  ┆ ATLAS\A3427 ┆ \\atlas.edf ┆ 43713024    │
│ ion Enviro   ┆             ┆ 15:04:16    ┆ 10:34:21    ┆ 4           ┆ .fr\\CO\DIP ┆             │
│ juin 20…     ┆             ┆             ┆             ┆             ┆ NN-FLA3\…   ┆             │
│ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ PTF3 Leviers ┆ .docx       ┆ 04/02/2025  ┆ 07/02/2025  ┆ ATLAS\D9935 ┆ \\atlas.edf ┆ 15816155    │
│ portes_DHO_0 ┆             ┆ 14:32:33    ┆ 15:55:33    ┆ 4           ┆ .fr\\CO\DIP ┆             │
│ 7-02-…       ┆             ┆             ┆             ┆             ┆ NN-FLA3\…   ┆             │
│ PTF3 Leviers ┆ .docx       ┆ 03/02/2025  ┆ 04/02/2025  ┆ ATLAS\LK2BA ┆ \\atlas.edf ┆ 15783255    │
│ portes_Relec ┆             ┆ 11:00:31    ┆ 14:31:31    ┆ 2CL         ┆ .fr\\CO\DIP ┆             │
│ ture …       ┆             ┆             ┆             ┆             ┆ NN-FLA3\…   ┆             │
│ [a relire]   ┆ .docx       ┆ 10/02/2025  ┆ 03/04/2025  ┆ ATLAS\D1267 ┆ \\atlas.edf ┆ 16775145    │
│ PTF3 Leviers ┆             ┆ 11:20:24    ┆ 11:10:13    ┆ 8           ┆ .fr\\CO\DIP ┆             │
│ portes…      ┆             ┆             ┆             ┆             ┆ NN-FLA3\…   ┆             │
│ [à relire]Ju ┆ .docx       ┆ 19/02/2025  ┆ 19/02/2025  ┆ ATLAS\JL5B1 ┆ \\atlas.edf ┆ 194355      │
│ stifications ┆             ┆ 11:25:50    ┆ 14:46:46    ┆ B6N         ┆ .fr\\CO\DIP ┆             │
│ de la…       ┆             ┆             ┆             ┆             ┆ NN-FLA3\…   ┆             │
│ ~$Leviers    ┆ .pptx       ┆ 02/04/2025  ┆ 02/04/2025  ┆ ATLAS\A4495 ┆ \\atlas.edf ┆ 0           │
│ Casses       ┆             ┆ 09:58:52    ┆ 10:01:48    ┆ 4           ┆ .fr\\CO\DIP ┆             │
│ Pressions -  ┆             ┆             ┆             ┆             ┆ NN-FLA3\…   ┆             │
│ C…           ┆             ┆             ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

shape: (1_802_054, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ Nom titre du ┆ Type        ┆ Date de     ┆ Date de     ┆ Nom du créa ┆ Chemin      ┆ Taille du   │
│ fichier      ┆ extension   ┆ création du ┆ dernière    ┆ teur/dernie ┆ d'accès     ┆ fichier     │
│ ---          ┆ de fichier  ┆ fichier     ┆ modificatio ┆ r modifi…   ┆ ---         ┆ ---         │
│ str          ┆ ---         ┆ ---         ┆ n           ┆ ---         ┆ str         ┆ str         │
│              ┆ str         ┆ str         ┆ ---         ┆ str         ┆             ┆             │
│              ┆             ┆             ┆ str         ┆             ┆             ┆             │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ ECFA070459.d ┆ .docx       ┆ 05/04/2019  ┆ 05/04/2019  ┆ O:S-1-5-21- ┆ \\atlas.edf ┆ 1027830     │
│ ocx          ┆             ┆ 11:15:34    ┆ 11:15:36    ┆ 2415383333- ┆ .fr\\CO\DIP ┆             │
│              ┆             ┆             ┆             ┆ 40638412…   ┆ NN-FLA3\…   ┆             │
│ Gestion      ┆ .pptx       ┆ 02/09/2020  ┆ 02/09/2020  ┆ O:S-1-5-21- ┆ \\atlas.edf ┆ 233513      │
│ bouteilles   ┆             ┆ 09:43:43    ┆ 10:12:59    ┆ 2415383333- ┆ .fr\\CO\DIP ┆             │
│ de gaz.pptx  ┆             ┆             ┆             ┆ 40638412…   ┆ NN-FLA3\…   ┆             │
│ Réchauffemen ┆ .docx       ┆ 16/05/2019  ┆ 16/05/2019  ┆ O:S-1-5-21- ┆ \\atlas.edf ┆ 1261520     │
│ t Climatique ┆             ┆ 14:32:47    ┆ 14:31:30    ┆ 2415383333- ┆ .fr\\CO\DIP ┆             │
│ -Trans…      ┆             ┆             ┆             ┆ 40638412…   ┆ NN-FLA3\…   ┆             │
│ S24-2018     ┆ .xlsx       ┆ 15/06/2018  ┆ 15/06/2018  ┆ O:S-1-5-21- ┆ \\atlas.edf ┆ 16383       │
│ stat         ┆             ┆ 14:53:52    ┆ 14:53:53    ┆ 2415383333- ┆ .fr\\CO\DIP ┆             │
│ AFA.xlsx     ┆             ┆             ┆             ┆ 40638412…   ┆ NN-FLA3\…   ┆             │
│ Sensibilisat ┆ .ppt        ┆ 23/07/2019  ┆ 24/07/2019  ┆ ATLAS\A3427 ┆ \\atlas.edf ┆ 43713024    │
│ ion Enviro   ┆             ┆ 15:04:16    ┆ 10:34:21    ┆ 4           ┆ .fr\\CO\DIP ┆             │
│ juin 20…     ┆             ┆             ┆             ┆             ┆ NN-FLA3\…   ┆             │
│ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ PTF3 Leviers ┆ .docx       ┆ 04/02/2025  ┆ 07/02/2025  ┆ ATLAS\D9935 ┆ \\atlas.edf ┆ 15816155    │
│ portes_DHO_0 ┆             ┆ 14:32:33    ┆ 15:55:33    ┆ 4           ┆ .fr\\CO\DIP ┆             │
│ 7-02-…       ┆             ┆             ┆             ┆             ┆ NN-FLA3\…   ┆             │
│ PTF3 Leviers ┆ .docx       ┆ 03/02/2025  ┆ 04/02/2025  ┆ ATLAS\LK2BA ┆ \\atlas.edf ┆ 15783255    │
│ portes_Relec ┆             ┆ 11:00:31    ┆ 14:31:31    ┆ 2CL         ┆ .fr\\CO\DIP ┆             │
│ ture …       ┆             ┆             ┆             ┆             ┆ NN-FLA3\…   ┆             │
│ [a relire]   ┆ .docx       ┆ 10/02/2025  ┆ 03/04/2025  ┆ ATLAS\D1267 ┆ \\atlas.edf ┆ 16775145    │
│ PTF3 Leviers ┆             ┆ 11:20:24    ┆ 11:10:13    ┆ 8           ┆ .fr\\CO\DIP ┆             │
│ portes…      ┆             ┆             ┆             ┆             ┆ NN-FLA3\…   ┆             │
│ [à relire]Ju ┆ .docx       ┆ 19/02/2025  ┆ 19/02/2025  ┆ ATLAS\JL5B1 ┆ \\atlas.edf ┆ 194355      │
│ stifications ┆             ┆ 11:25:50    ┆ 14:46:46    ┆ B6N         ┆ .fr\\CO\DIP ┆             │
│ de la…       ┆             ┆             ┆             ┆             ┆ NN-FLA3\…   ┆             │
│ ~$Leviers    ┆ .pptx       ┆ 02/04/2025  ┆ 02/04/2025  ┆ ATLAS\A4495 ┆ \\atlas.edf ┆ 0           │
│ Casses       ┆             ┆ 09:58:52    ┆ 10:01:48    ┆ 4           ┆ .fr\\CO\DIP ┆             │
│ Pressions -  ┆             ┆             ┆             ┆             ┆ NN-FLA3\…   ┆             │
│ C…           ┆             ┆             ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

12 mins :
100 workers : 378 files : 468 mb
200 workers : 463 files : 782 mb

In [1]:
import pandas as pd
import polars as pl
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
import sys

# Add the project root directory to sys.path
sys.path.append(str(Path().resolve().parent))
from src.constants.paths import SECRET_PATH


from src.processing.pde_ple import PDE, PLE

In [5]:
import chardet
def detect_encoding(file_path):
    with open(file_path, "rb") as f:
        result = chardet.detect(f.read())
    return result["encoding"]
detect_encoding(r"C:\Users\e58883\uc202\uc202-ipn-rex\notebooks\uploaded_log.txt")

'MacRoman'

In [ ]:


# Chemins
s3_base_path = "s3://bkt-pud-uc/uc202-rex/FA3_useful_files_final"
csv_s3_path = "s3://bkt-pud-uc/uc202-rex/FA3_useful_files.csv"
local_base_dir = Path(r"\\atlas.edf.fr\CO\DIPNN-FLA3\Services.004")
upload_log_path = Path(r"C:\Users\e58883\uc202\uc202-ipn-rex\notebooks\uploaded_log.txt")  # local log file

# Lecture du fichier CSV
#df = PLE.s3.read_dataframe(csv_s3_path, file_format="csv")
df=pl.read_csv(r"C:\Users\e58883\Downloads\FA3_useful_files.csv")
print('read done')
# Vérifie la présence de la colonne attendue
if "Chemin d'accès" not in df.columns:
    raise ValueError("Colonne 'Chemin d'accès' manquante dans le fichier CSV.")

# Fichiers déjà uploadés (log)
if upload_log_path.exists():
    with open(upload_log_path, "r", encoding="MacRoman") as f:
        already_uploaded = set(line.strip() for line in f)
else:
    already_uploaded = set()


# Fonction d'upload avec log
def upload_file(file_path_str: str):
    file_path_str = file_path_str.replace("\\", "/").replace(":/", "://", 1)
    try:
        local_path_without_base = file_path_str.replace(
            "//atlas.edf.fr//CO/DIPNN-FLA3", ""
        )

# Construct the final S3 target path
        s3_target_path = f"{s3_base_path}{local_path_without_base}"
        PDE.s3.upload(local_file=file_path_str, path=s3_target_path)
        with open(upload_log_path, "a", encoding="utf-8") as log:
            log.write(Path(file_path_str).as_posix() + "\n")
        #return f"Uploaded: {file_path}"
    except Exception as e:
        return f"Error with {file_path_str}: {e}"


# Liste à uploader (exclure déjà uploadés)
all_paths = df["Chemin d'accès"].drop_nulls().unique().to_list()
files_to_upload = [p for p in all_paths if p not in already_uploaded]

del df

print(f"Total remaining to upload: {len(files_to_upload)}")

# Upload en parallèle
max_workers = 250
with ThreadPoolExecutor(max_workers=max_workers) as executor:
    futures = {
        executor.submit(upload_file, file_path): file_path
        for file_path in files_to_upload
    }

    for future in as_completed(futures):
        print(future.result())

read done
Total remaining to upload: 1802046
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
Error with //atlas.edf.fr//CO/DIPNN-FLA3/Services.004/W-Lot-Ingenierie-Locale.023/100 - Etudes VRD Site/- 02 - Réferentiel/- 4 - Transfert CNEN vers AFA/03 Etudes/01 - Etudes réseaux/01 Réseau RGC/04 - Réseaux existants/parcelles 208-308.pdf: [Errno 2] No such file or directory: '//atlas.edf.fr//CO/DIPNN-FLA3/Services.004/W-Lot-Ingenierie-Locale.023/100 - Etudes VRD Site/- 02 - Réferentiel/- 4 - Transfert CNEN vers AFA/03 Etudes/01 - Etudes réseaux/01 Réseau RGC/04 - Réseaux existants/parcelles 208-308.pdf'
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
Error with //atlas.edf.fr//CO/DIPNN-FLA3/Services.004/W-Lot-Ingenierie-Locale.023/06 - FAC FNC/FAC_FNC_YR5111_CLEMESSY/AAAA-SCHEMAS-TYPE - MAJ du 28-04-21/302 Nonenclatures des matériels &  304 schéma types/EXE 302 503 PREL M_10_503_SH_12_105_30_76_Sch+®ma type ZAEL-DLEH.pdf: [Errno 2] No such file or directory: '//atlas.edf.fr//CO/DIPNN-FLA3/Services.004/W-Lot-Ingenierie-Locale.023/06 - FAC FNC/FAC_FNC_YR5111_CLEMESSY/AAAA-SCHEMAS-TYPE - MAJ du 28-04-21/302 Nonenclatures des matériels &  304 schéma types/EXE 302 503 PREL M_10_503_SH_12_105_30_76_Sch+®ma type ZAEL-DLEH.pdf'
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None

1802046

In [9]:
file.as_posix()

'C:/Users/e58883/Downloads/test/test.txt'

In [5]:
S3_test_path = "s3://bkt-pud-uc/uc202-rex/test.txt"
local_file_dir = r"C:\Users\e58883\Downloads\test\test.txt"

PLE.s3.connection.upload(lpath=local_file_dir, rpath=S3_test_path)

OSError: [Errno 5] An error occurred (BadRequest) when calling the PutObject operation: trailing checksum is not supported

In [ ]:
with local_file.open("rb") as local_f:
    PLE.s3.connection.upload(lpath=str(local_file), rpath=S3_test_path,checksum_algorithm=False)

AttributeError: '_io.BufferedReader' object has no attribute 'startswith'

In [4]:
from docx import Document
from pathlib import Path


def read_docx_tables(file_path):
    # Load the document
    doc = Document(file_path)

    # Extract and print text from each table
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                print(cell.text)

local_file_dir = r"\\atlas.edf.fr\CO\dipnn-fla3\Services.004\G-Environnement.007"
local_file = Path(local_file_dir, "ECFA070459.docx")

read_docx_tables(local_file)

Rédaction
Contrôle
Approbation
Visa final (*)
STEWART Clare
SILVESTRE Nadine
GILLOT Pierre-Yves

(*) La présence de cette icône atteste que le document a été approuvé par un circuit de signature électronique
(*) La présence de cette icône atteste que le document a été approuvé par un circuit de signature électronique
(*) La présence de cette icône atteste que le document a été approuvé par un circuit de signature électronique
(*) La présence de cette icône atteste que le document a été approuvé par un circuit de signature électronique
Activité Importante pour la Protection des intérêts (AIP ou NON AIP)
 ou document Important Pour la Sûreté (IPS ou NON IPS)
Activité Importante pour la Protection des intérêts (AIP ou NON AIP)
 ou document Important Pour la Sûreté (IPS ou NON IPS)
Activité Importante pour la Protection des intérêts (AIP ou NON AIP)
 ou document Important Pour la Sûreté (IPS ou NON IPS)
Activité Importante pour la Protection des intérêts (AIP ou NON AIP)
 ou document Important Pour la Sûreté (IPS ou NON IPS)
NAIP
NAIP
NAIP
Prédiffusion formalisée :
OUI

Adressée à :

NON

Imputation :






Code classement EDF :






Langue :
fr_FR
fr_FR
fr_FR
fr_FR
fr_FR
fr_FR
Accessibilité :
INTERNE
INTERNE
INTERNE
INTERNE
INTERNE
INTERNE
Applicabilité :
\
\
\
\
\
\
Modèle de sécurité :
20 - EPR N - Utilisateurs EDF + non EDF : autorisés par l'unité pilote EPR
20 - EPR N - Utilisateurs EDF + non EDF : autorisés par l'unité pilote EPR
20 - EPR N - Utilisateurs EDF + non EDF : autorisés par l'unité pilote EPR
20 - EPR N - Utilisateurs EDF + non EDF : autorisés par l'unité pilote EPR
20 - EPR N - Utilisateurs EDF + non EDF : autorisés par l'unité pilote EPR
20 - EPR N - Utilisateurs EDF + non EDF : autorisés par l'unité pilote EPR
Archivage :
100
100
100
100
100
100
Indice
Etat de validité
Date Approbation
Motif du changement d’indice
Modifications apportées
A

11/06/2007
Emission

B

15/05/2013
Mise à jour suite à :
- la mise en eau du chenal le 23/10/12 et la suppression du puisard fond de fouille
- la mise en service du bâtiment HX et de l’émissaire R15
- le changement  de l’organisation des astreintes EDF
- la publication de l’arrêté du 7 février 2012 « arrêté INB »
Ajouts :
- actions sur les vannes pelles dans le bâtiment HX
- notion d’incendie dans les situations d’urgence environnementales
- nouvel étiquetage des produits dangereux
- actions PCD2
- nouveaux documents de référence
Mise à jour des annexes, notamment :
- mise à jour de la fiche message incident environnement
- mise à jour de la fiche réflexe environnement
C

25/03/2016
Mise à jour suite au rex des incidents et exercices de 2013 à 2015
Refonte de l’INS, Mise à jour de toutes les annexes, notamment les fiches messages incident environnement  + Ajout d’informations pour mieux gérer les urgences (appui logistique, contacts, modèles BSD, conseils,…)
D

27/09/2017
Mise à jour suite à la modification du fonctionnement du HX et à la mise à jour des fiches réflexes Environnement et d’astreinte
Refonte de l’INS, mise à jour des annexes (fiche réflexe Environnement, consignes d’astreintes entre autre).
E

21/01/2019
Mise à jour suite aux changements des astreintes DPFA3/DPN
Principaux modifications :
Suppression du rôle PCD2 DPFA3 repris par la DPNT en tant que Directeur des Secours
Mise à jour des moyens anti-pollution à disposition et leur localisation
Mise à jour de la liste d’annexes
Suppression de la FRE « aire de transit »
18
: 18 interne au site EDF en Salle de Commande Tranche 3 EPR
DPFA3
: Direction de Projet Flamanville 3
BSD
CCL
: Bordereau de Suivi de Déchets
: Centre de Crise Local
DPNT
: Division Production Nucléaire et Thérmique
DOIS
: Document d’Orientation Intervention et Secours
Equipe Renfort
: Ancienne EAS (Equipe Appui Secours)
EIE
: Evènement Intéressant l’Environnement
EPI
: Equipements de Protection Individuelle
ESE
: Evènement Significatif pour l’Environnement
ICPE
NAC
: Installation Classée pour la Protection de l’Environnement
: Note d’Application Commune
PCD
: Poste de Commandement Direction
PGAC
: Prestation Globale d’Assistance Chantier
PAS
: Poste d’Accès Secondaire
PCOM
: Poste Commandement Opérationnel Mobile
PS
: Protection de Site
Chef de Poste PS
: Chef de poste Protection de site
POE
: Pôle Opérationnel Exploitation
PRS
: Poste de Ralliement des Secours
REX
SdC
: Retour d’Expérience
: Salle des Commandes
SEH
: Recueil des huiles et des effluents hydrocarbonés
SEO
: Eaux perdues à l’égout (réseau d’eaux pluviales voirie, d’eaux pluviales toiture, eaux usées)
SP
: Sapeur Pompiers
VSE
: Visite Sécurité Environnement
Ancien étiquetage

Nouvel étiquetage

CAS DE POLLUTION
Risques et EPI
Risques et EPI
MOYENS ANTIPOLLUTION
MOYENS ANTIPOLLUTION
CAS DE POLLUTION
Lesquels
Où les trouver ?
Lesquels
Où les trouver ?
Déversement d’hydrocarbures
(huile, fuel, gasoil,…)
Risques : inflammable, dangereux pour l’homme (essence)

Gants





Dans le kit
Kit hydrocarbures
(kit blanc)
TOUS les postes de secours du chantier
Magasin
Véhicules PS, PCOM et Equipe Renfort
Déversement d’hydrocarbures
(huile, fuel, gasoil,…)
Risques : inflammable, dangereux pour l’homme (essence)

Gants





Dans le kit
Sable absorbant
TOUS les postes de secours du chantier
Magasin Véhicule PS
Déversement d’hydrocarbures
(huile, fuel, gasoil,…)
Lunettes
EPI
Plaque d’obturation d’égout
Bungalow gestion des pollutions, aire de transit
Véhicule PS





Déversement de produit chimique
(hors acide/produit corrosif)
Risques : selon pictogrammes page suivante

Kit tous produit
(kit gris)
Véhicules PS,  PCOM et Equipe Renfort
Magasin
Déversement de produit chimique
(hors acide/produit corrosif)
Gants
Dans le kit
Sable absorbant
TOUS les postes de secours du chantier
Magasin
Véhicule PS
Déversement de produit chimique
(hors acide/produit corrosif)
Lunettes
EPI
Plaque d’obturation d’égout
Bungalow gestion des pollutions, aire de transit
Véhicule PS





Déversement d’acide ou de produit corrosif

ou
Risques : brulures

Kit tous produit
(kit gris)
Véhicules PS, PCOM et Equipe Renfort
Magasin
Déversement d’acide ou de produit corrosif

ou
Gants de protection contre l’acide
Véhicule EAS,
Magasin
Sable absorbant
TOUS les postes de secours du chantier
Magasin
Déversement d’acide ou de produit corrosif

ou
Lunettes
EPI
Plaque d’obturation d’égout
Bungalow gestion des pollutions, aire de transit
Véhicule PS





Déversement de produit non identifié
(pas de pictogramme)
Gants de protection contre l’acide
Véhicule EAS,
Magasin
Kit tous produit
(kit gris)
Véhicules PS, PCOM et Equipe Renfort
Magasin
Déversement de produit non identifié
(pas de pictogramme)
Tenue de protection papier
Véhicule EAS,
Magasin
Sable absorbant
TOUS les postes de secours du chantier
Magasin
Véhicule PS
Déversement de produit non identifié
(pas de pictogramme)
Lunettes
EPI
Plaque d’obturation d’égout
Bungalow gestion des pollutions, aire de transit
Véhicule PS
Matériels disponibles
Fournisseurs possibles
Contacts
Numéros d’urgence
Interventions heures non ouvrées

SADE
M. ERNOULT Nicolas
06.09.73.81.30


BEAUSSIRE
M. BEAUSSIRE Christophe
02.33.71.40.20

Balayeuse camion
VEOLIA PROPRETE
M. Mounir AABBADI
M. LAUVRAY Sébastien
06.29.02.81.99
06.15.19.86.05

Pompage/Nettoyage
Voiries/fosses
AIT
M BLED Yves
Agence de TOURLAVILLE
Agence de VALOGNES
06 30 49 92 26
02.33.88.60.00
02 33 94 19 89 (astreinte)
X
Balai motorisé
SADE
M. ERNOULT Nicolas
06.09.73.81.30

Pompage : pompe serpillère ou autres
ADF
M WAKIL Chakib
02 33 52 89 02
06 61 39 06 76

Cubitainer 1m3
ADF
M WAKIL Chakib
02 33 52 89 02
06 61 39 06 76

Barrières, GBA en plastique remplis par de l’eau ensuite
SADE
M. ERNOULT Nicolas
06.09.73.81.30

Barrières, GBA en plastique remplis par de l’eau ensuite
ADF
M WAKIL Chakib
02 33 52 89 02
06 61 39 06 76

Hydrocurage,
Camion-citerne ADR pour eau souillée
AIT
M BLED Yves
Agence de TOURLAVILLE
Agence de VALOGNES
06 30 49 92 26
02.33.88.60.00
02 33 94 19 89 (astreinte)
x




n° fiche
reflexe
objet
référence du document
documents associés
E
ENVIRONNEMENT
INS EPR 614 Ind E
Vannes pelles du HX (ECFA125415)
Obturateurs gonflables (ECFA071339)
DOIS (Document Orientation Incendie et Secours)
Interne EDF
- Direction Division + Cabinet de la Division
- Cabinet DPI
- Direction CNEN
- PCD1 CNPE
- Délégation Régionale
Externe EDF
- Préfecture
- Sous-Préfecture
- Préfecture Maritime
- ASN division Caen
- Président de la Communauté de l’Agglomération du Cotentin
- DDTM de St-Lô (par téléphone)
- DML de Cherbourg (par téléphone)
- CROSS de Jobourg (par téléphone)
- DREAL (par téléphone)




n° fiche
reflexe
objet
référence du document
documents associés
E
ENVIRONNEMENT
INS EPR 614 Ind E
Vannes pelles du HX (ECFA125415)
Obturateurs gonflables (ECFA071339)
DOIS (Document Orientation Incendie et Secours)
ASN
ASN division  Caen
Préfecture
Sous-Préfecture
Préfecture Maritime

DDTM St Lô
DML Cherbourg
Le CROSS-MA de Jobourg
DREAL




n° fiche
reflexe
objet
référence du document
documents associés
E
ENVIRONNEMENT
INS EPR 614 Ind E
Vannes pelles du HX (ECFA125415)
Obturateurs gonflables (ECFA071339)
DOIS (Document Orientation Incendie et Secours)
FICHE D’INFORMATION - GESTION DES SITUATIONS D’URGENCES ENVIRONNEMENTALES
DATE : 						HEURE :
NOM & QUALITE :			                       	Visa :


Description de l’impact sur l’environnement :







Causes potentielles :





















n° fiche
reflexe
objet
référence du document
documents associés
E
ENVIRONNEMENT
INS EPR 614 Ind E
Vannes pelles du HX (ECFA125415)
Obturateurs gonflables (ECFA071339)
DOIS (Document Orientation Incendie et Secours)